"""Append-only audit log of every decision the gate makes.

Every resolution, every execution, every human override, and every
re-examination lands here as an immutable record. The log is the source of
truth for the metrics module and for the override handler (which reads back the
other calls in a trace). It can be replayed from a JSONL file: the decision was
made by a pure resolver, so replaying the records reproduces the reasoning.
"""

from __future__ import annotations

import json
from dataclasses import asdict, dataclass, field
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Iterable, Iterator, Literal

from .consequence import Consequence, Tier

Outcome = Literal["executed", "queued", "refused", "overridden"]


@dataclass(frozen=True)
class Decision:
    """The record the resolver's verdict becomes once the gate acts on it."""

    trace_id: str
    call_id: str
    tool: str
    arguments: dict
    confidence: float
    consequence: Consequence
    tier: Tier
    reason: str  # human-readable, generated by the resolver
    policy_applied: str | None
    timestamp: datetime
    outcome: Outcome | None = None


@dataclass(frozen=True)
class AuditEntry:
    """A decision plus the operational facts the metrics need. `context` carries
    the linkage keys (target entity, source record, retrieved context) the
    override handler uses to find calls that shared a rejected call's context."""

    seq: int
    decision: Decision
    context: dict = field(default_factory=dict)
    cost: float = 0.0
    gate_overhead_ms: float = 0.0
    tool_ms: float | None = None
    success: bool | None = None


# --- clocks ----------------------------------------------------------------
# Decisions are timestamped. For demos we want a deterministic, paste-stable
# clock so README output doesn't churn; in production you'd use SystemClock.


class SystemClock:
    def now(self) -> datetime:
        return datetime.now(timezone.utc)


class StepClock:
    """Deterministic clock: starts at a fixed instant, advances one step per
    reading. Keeps demo transcripts reproducible."""

    def __init__(self, start: datetime | None = None, step_seconds: float = 1.0):
        self._t = start or datetime(2026, 1, 1, 9, 0, 0, tzinfo=timezone.utc)
        self._step = timedelta(seconds=step_seconds)

    def now(self) -> datetime:
        t = self._t
        self._t = self._t + self._step
        return t


class AuditLog:
    def __init__(self, path: str | Path | None = None):
        self._entries: list[AuditEntry] = []
        self._path = Path(path) if path else None
        self._seq = 0
        if self._path:
            self._path.write_text("")  # truncate; append-only from here

    def record(
        self,
        decision: Decision,
        *,
        context: dict | None = None,
        cost: float = 0.0,
        gate_overhead_ms: float = 0.0,
        tool_ms: float | None = None,
        success: bool | None = None,
    ) -> AuditEntry:
        entry = AuditEntry(
            seq=self._seq,
            decision=decision,
            context=context or {},
            cost=cost,
            gate_overhead_ms=gate_overhead_ms,
            tool_ms=tool_ms,
            success=success,
        )
        self._seq += 1
        self._entries.append(entry)
        if self._path:
            with self._path.open("a") as fh:
                fh.write(json.dumps(_entry_to_dict(entry)) + "\n")
        return entry

    def all(self) -> list[AuditEntry]:
        return list(self._entries)

    def by_trace(self, trace_id: str) -> list[AuditEntry]:
        return [e for e in self._entries if e.decision.trace_id == trace_id]

    def __iter__(self) -> Iterator[AuditEntry]:
        return iter(self._entries)

    def __len__(self) -> int:
        return len(self._entries)

    @staticmethod
    def replay(path: str | Path) -> list[AuditEntry]:
        entries: list[AuditEntry] = []
        for line in Path(path).read_text().splitlines():
            if line.strip():
                entries.append(_entry_from_dict(json.loads(line)))
        return entries


def _entry_to_dict(entry: AuditEntry) -> dict:
    d = asdict(entry)
    dec = d["decision"]
    dec["tier"] = entry.decision.tier.value
    dec["timestamp"] = entry.decision.timestamp.isoformat()
    return d


def _entry_from_dict(d: dict) -> AuditEntry:
    dec = d["decision"]
    decision = Decision(
        trace_id=dec["trace_id"],
        call_id=dec["call_id"],
        tool=dec["tool"],
        arguments=dec["arguments"],
        confidence=dec["confidence"],
        consequence=Consequence(**dec["consequence"]),
        tier=Tier(dec["tier"]),
        reason=dec["reason"],
        policy_applied=dec["policy_applied"],
        timestamp=datetime.fromisoformat(dec["timestamp"]),
        outcome=dec["outcome"],
    )
    return AuditEntry(
        seq=d["seq"],
        decision=decision,
        context=d.get("context", {}),
        cost=d.get("cost", 0.0),
        gate_overhead_ms=d.get("gate_overhead_ms", 0.0),
        tool_ms=d.get("tool_ms"),
        success=d.get("success"),
    )
